import { useEffect, useMemo, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { StitchBottomNav, StitchTopBar } from '../components/StitchChrome';
import { getSession } from '../lib/api';
import { getAccessToken } from '../lib/session';
import { Stitch } from '../lib/stitch-theme';
import { STITCH_SUPPLIED_SCREEN_COUNT, stitchPurpose, stitchScreensForRoles } from '../lib/stitch-screen-catalog';

export default function StitchCatalog(){const[roles,setRoles]=useState<string[]>([]);const[authenticated,setAuthenticated]=useState(false);const[query,setQuery]=useState('');const[showDesign,setShowDesign]=useState(false);useEffect(()=>{let active=true;async function loadIdentity(){const token=await getAccessToken();if(!active||!token)return;setAuthenticated(true);try{const session=await getSession();if(active)setRoles(session.roles??[])}catch{}}void loadIdentity();return()=>{active=false}},[]);const screens=useMemo(()=>{const needle=query.trim().toLowerCase();return stitchScreensForRoles(roles,authenticated).filter((screen)=>showDesign||screen.status==='live').filter((screen)=>!needle||`${screen.title} ${screen.domain} ${screen.roles.join(' ')}`.toLowerCase().includes(needle))},[roles,authenticated,query,showDesign]);const groups=useMemo(()=>{const map=new Map<string,typeof screens>();for(const screen of screens){const list=map.get(screen.domain)??[];list.push(screen);map.set(screen.domain,list)}return[...map.entries()].sort(([a],[b])=>a.localeCompare(b))},[screens]);return <SafeAreaView style={s.safe}><StitchTopBar title="iRespond surfaces" showCatalog={false}/><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.eyebrow}>CANONICAL STITCH FRONTEND</Text><Text style={s.title}>Every live capability has a designed home.</Text><Text style={[s.body,{color:Stitch.color.primaryFixed}]}>The supplied Google Stitch package contains {STITCH_SUPPLIED_SCREEN_COUNT} visual contracts. iRespond extends that language only where the backend already exposes a real capability. Planned designs never masquerade as working production features.</Text></View><TextInput accessibilityLabel="Search iRespond surfaces" placeholder="Search screens, roles or domains" value={query} onChangeText={setQuery} style={s.search}/><View style={s.toggleRow}><View style={{flex:1}}><Text style={s.toggleTitle}>Show design backlog</Text><Text style={s.small}>Off by default. Backlog screens have no fabricated actions.</Text></View><Switch value={showDesign} onValueChange={setShowDesign}/></View>{groups.map(([domain,items])=><View key={domain} style={s.group}><Text style={s.domain}>{domain.replaceAll('-',' ').toUpperCase()}</Text>{items.map((screen)=><Pressable key={screen.id} style={s.card} onPress={()=>router.push(`/stitch/${screen.id}` as never)} accessibilityRole="button"><View style={s.cardTop}><Text style={s.cardTitle}>{screen.title}</Text><Text style={screen.status==='live'?s.live:s.design}>{screen.status==='live'?'LIVE':'DESIGN'}</Text></View><Text numberOfLines={2} style={s.body}>{stitchPurpose(screen)}</Text><Text style={s.roles}>{screen.roles.join(' · ')}</Text></Pressable>)}</View>)}</ScrollView><StitchBottomNav/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Stitch.color.background},content:{padding:Stitch.space.screen,gap:Stitch.space.base,paddingBottom:36},hero:{backgroundColor:Stitch.color.primary,borderRadius:Stitch.radius.hero,padding:Stitch.space.lg,gap:Stitch.space.sm},eyebrow:{...Stitch.type.eyebrow,color:Stitch.color.secondaryFixedDim},title:{...Stitch.type.headline,color:Stitch.color.onPrimary},body:{...Stitch.type.body,color:Stitch.color.onSurfaceVariant},search:{minHeight:Stitch.control.primaryHeight,borderWidth:1,borderColor:Stitch.color.outlineVariant,backgroundColor:Stitch.color.surfaceLowest,borderRadius:Stitch.radius.md,paddingHorizontal:Stitch.space.base,color:Stitch.color.onSurface},toggleRow:{backgroundColor:Stitch.color.surfaceLowest,borderRadius:Stitch.radius.lg,padding:Stitch.space.card,flexDirection:'row',alignItems:'center',gap:Stitch.space.md,borderWidth:1,borderColor:Stitch.color.outlineVariant},toggleTitle:{...Stitch.type.bodyBold,color:Stitch.color.primary},small:{...Stitch.type.footnote,color:Stitch.color.onSurfaceVariant,marginTop:3},group:{gap:Stitch.space.sm},domain:{...Stitch.type.eyebrow,color:Stitch.color.secondary,marginTop:Stitch.space.sm},card:{backgroundColor:Stitch.color.surfaceLowest,borderRadius:Stitch.radius.lg,borderWidth:1,borderColor:Stitch.color.outlineVariant,padding:Stitch.space.card,gap:Stitch.space.sm},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:Stitch.space.sm,alignItems:'flex-start'},cardTitle:{...Stitch.type.card,color:Stitch.color.primary,flex:1},live:{...Stitch.type.tag,color:Stitch.color.secondary,backgroundColor:Stitch.color.secondaryContainer,borderRadius:Stitch.radius.full,paddingHorizontal:8,paddingVertical:4},design:{...Stitch.type.tag,color:Stitch.color.onSurfaceVariant,backgroundColor:Stitch.color.surfaceContainer,borderRadius:Stitch.radius.full,paddingHorizontal:8,paddingVertical:4},roles:{...Stitch.type.footnote,color:Stitch.color.outline}});
