import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getAccessToken } from '../lib/session';

type Offer={id:string;projectId:string;contributionNeedId:string;contributorId:string;kind:string;note:string;availabilityNote:string;status:'offered'|'accepted'|'declined'|'withdrawn'|'fulfilled';createdAt:string;updatedAt:string};

export default function MyContributions(){
  const[offers,setOffers]=useState<Offer[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState<string|null>(null);
  async function load(){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');if(!base){setError('The contribution API is not configured on this build.');setLoading(false);return}const token=await getAccessToken();if(!token){router.replace('/signin');return}setLoading(true);setError('');try{const r=await fetch(`${base}/v1/me/contribution-offers`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===401){router.replace('/signin');return}if(!r.ok)throw new Error(String(r.status));setOffers(await r.json() as Offer[])}catch{setError('Your contribution offers could not be loaded. Check connectivity and try again.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function withdraw(offer:Offer){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');const token=await getAccessToken();if(!base||!token){router.push('/signin');return}setBusy(offer.id);try{const r=await fetch(`${base}/v1/contribution-offers/${encodeURIComponent(offer.id)}/withdraw`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(String(r.status));const updated=await r.json() as Offer;setOffers(current=>current.map(v=>v.id===updated.id?updated:v))}catch{Alert.alert('Offer not withdrawn','Only an offer that is still awaiting a steward decision can be withdrawn.')}finally{setBusy(null)}}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.eyebrow}>MY RESPONSE</Text><Text style={styles.title}>My contribution offers</Text><Text style={styles.intro}>Track what you offered, what a project accepted, and what has been fulfilled. An offer is not a commitment until a project steward accepts it.</Text>{loading&&<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading your offers…</Text></View>}{!!error&&<View style={styles.notice}><Text style={styles.noticeTitle}>Unable to load</Text><Text style={styles.muted}>{error}</Text><Pressable onPress={load}><Text style={styles.link}>Try again</Text></Pressable></View>}{!loading&&!error&&offers.length===0&&<View style={styles.empty}><Text style={styles.emptyTitle}>No offers yet</Text><Text style={styles.muted}>When you respond to a Project Room with time, skills, materials, access, care or another ability, it will appear here.</Text></View>}{offers.map(o=><View key={o.id} style={styles.card}><View style={styles.row}><Text style={styles.kind}>{human(o.kind)}</Text><Text style={[styles.status,statusStyle(o.status)]}>{human(o.status)}</Text></View><Text style={styles.note}>{o.note||'Contribution offer'}</Text>{!!o.availabilityNote&&<Text style={styles.muted}>{o.availabilityNote}</Text>}<Pressable onPress={()=>router.push({pathname:'/project/[id]',params:{id:o.projectId}})}><Text style={styles.link}>Open Project Room →</Text></Pressable>{o.status==='offered'&&<Pressable style={[styles.withdraw,busy===o.id&&styles.disabled]} disabled={busy===o.id} onPress={()=>withdraw(o)}><Text style={styles.withdrawText}>{busy===o.id?'Withdrawing…':'Withdraw offer'}</Text></Pressable>}{o.status==='accepted'&&<Text style={styles.accepted}>Accepted means the project is now relying on this response. Contact/coordination workflows will be expanded in the next delivery slices.</Text>}{o.status==='fulfilled'&&<Text style={styles.fulfilled}>Fulfilled — this response has been recorded as delivered.</Text>}</View>)}</ScrollView></SafeAreaView>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function statusStyle(v:Offer['status']){if(v==='fulfilled')return styles.statusDone;if(v==='accepted')return styles.statusAccepted;if(v==='declined'||v==='withdrawn')return styles.statusClosed;return styles.statusPending}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,gap:14,paddingBottom:50},back:{color:'#2D6E9F',fontWeight:'800'},eyebrow:{color:'#2D7A56',fontWeight:'900',letterSpacing:1.5},title:{fontSize:29,lineHeight:35,fontWeight:'900',color:'#17324D'},intro:{color:'#667788',lineHeight:21},center:{alignItems:'center',paddingVertical:28,gap:8},muted:{color:'#667788',lineHeight:20},notice:{backgroundColor:'#FFF0EF',padding:16,borderRadius:16,gap:6},noticeTitle:{fontWeight:'900',color:'#8A352F'},empty:{backgroundColor:'#EEF3F7',padding:16,borderRadius:16,gap:5},emptyTitle:{fontWeight:'900',color:'#17324D'},card:{backgroundColor:'white',borderRadius:17,padding:16,gap:9},row:{flexDirection:'row',justifyContent:'space-between',gap:10},kind:{color:'#2D6E9F',fontWeight:'900'},status:{fontWeight:'900',fontSize:12},statusPending:{color:'#9A6423'},statusAccepted:{color:'#2D6E9F'},statusDone:{color:'#24724D'},statusClosed:{color:'#7B6670'},note:{color:'#17324D',fontSize:17,fontWeight:'900'},link:{color:'#2D6E9F',fontWeight:'800'},withdraw:{borderWidth:1,borderColor:'#C88780',borderRadius:12,padding:11},withdrawText:{color:'#8A352F',fontWeight:'900',textAlign:'center'},disabled:{opacity:.5},accepted:{backgroundColor:'#EAF2F8',padding:11,borderRadius:11,color:'#355D78',lineHeight:18},fulfilled:{backgroundColor:'#E9F5EF',padding:11,borderRadius:11,color:'#245840',fontWeight:'800'}})
