import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { StitchBottomNav, StitchTopBar } from '../components/StitchChrome';
import { Stitch } from '../lib/stitch-theme';
import { flushNeedQueue, pendingNeedCount } from '../lib/sync';

const urgentNeeds=[
 {id:'water-001',status:'VETTED',title:'Broken Community Well',description:'Main pump housing is cracked, affecting water supply for nearby households.',distance:'0.2 mi',icon:'water-outline' as const},
 {id:'school-001',status:'REPORTED',title:'School Library Lighting',description:'The reading room needs safe lighting restored before evening study sessions.',distance:'0.7 mi',icon:'book-outline' as const}
];
const activeProjects=[
 {id:'school-001',sdg:'SDG 4: Quality Education',title:'District School Supply Drive',description:'Community supplies and volunteer coordination for the next distribution milestone.',progress:85,label:'Funding / Supplies'},
 {id:'care-001',sdg:'SDG 11: Sustainable Cities',title:'Neighbourhood Care Rota',description:'Weekly volunteer coordination for elderly neighbours and home support.',progress:45,label:'Volunteers Needed'}
];

export default function ImpactFeed(){
 const[pendingSync,setPendingSync]=useState(0);const[refreshing,setRefreshing]=useState(false);const[query,setQuery]=useState('');
 async function sync(){await flushNeedQueue();setPendingSync(await pendingNeedCount())}useEffect(()=>{void sync()},[]);async function refresh(){setRefreshing(true);try{await sync()}finally{setRefreshing(false)}}
 return <SafeAreaView style={s.safe} edges={['top','left','right']}><View style={s.screen}><StitchTopBar/><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void refresh()}/>}>
  {pendingSync>0&&<Pressable style={s.syncBanner} onPress={()=>void refresh()}><Ionicons name="cloud-upload-outline" size={21} color={Stitch.color.tertiary}/><View style={{flex:1}}><Text style={s.syncTitle}>{pendingSync} observation{pendingSync===1?'':'s'} waiting to sync</Text><Text style={s.syncText}>Tap to retry. Your report remains safely queued on this device.</Text></View></Pressable>}
  <View style={s.searchRow}><View style={s.searchBox}><Ionicons name="search" size={21} color={Stitch.color.onSurfaceVariant}/><TextInput style={s.searchInput} placeholder="Search local needs…" placeholderTextColor="#6D7580" value={query} onChangeText={setQuery}/></View><Pressable style={s.nearButton} onPress={()=>router.push('/needmap')}><Ionicons name="navigate-outline" size={19} color={Stitch.color.primary}/><Text style={s.nearText}>Near me</Text></Pressable></View>
  <View style={s.viewToggle}><Pressable style={[s.toggle,s.toggleOn]} onPress={()=>router.push('/needmap')}><Ionicons name="map-outline" size={17} color={Stitch.color.onPrimaryContainer}/><Text style={s.toggleOnText}>Map</Text></Pressable><Pressable style={s.toggle}><Ionicons name="list" size={18} color={Stitch.color.onSurfaceVariant}/><Text style={s.toggleText}>List</Text></Pressable></View>
  <Pressable style={s.mapCanvas} onPress={()=>router.push('/needmap')} accessibilityRole="button"><View style={s.mapGrid}/><View style={[s.pin,{left:'28%',top:'28%'}]}><Ionicons name="water" size={18} color={Stitch.color.primary}/></View><View style={[s.pin,s.pinGreen,{left:'68%',top:'55%'}]}><Ionicons name="school" size={18} color={Stitch.color.secondary}/></View><View style={s.mapCaption}><Text style={s.mapCaptionTitle}>Live NeedMap</Text><Text style={s.mapCaptionText}>Open the geospatial API for nearby verified and observed needs.</Text></View><View style={s.mapAction}><Ionicons name="locate" size={23} color={Stitch.color.primary}/></View></Pressable>
  <SectionHeader title="Urgent Needs" meta="0.5 mi radius"/>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.horizontalCards}>{urgentNeeds.map(need=><Pressable key={need.id} style={s.needCard} onPress={()=>router.push(`/need/${need.id}`)}><View style={s.cardTop}><View style={[s.statusBadge,need.status==='REPORTED'&&s.statusReported]}><Ionicons name={need.status==='VETTED'?'checkmark-done-outline':'alert-circle-outline'} size={14} color={need.status==='VETTED'?Stitch.color.tertiary:Stitch.color.error}/><Text style={[s.statusText,need.status==='REPORTED'&&s.statusReportedText]}>{need.status}</Text></View><View style={s.distance}><Ionicons name="location-outline" size={14} color={Stitch.color.onSurface}/><Text style={s.distanceText}>{need.distance}</Text></View></View><View style={s.needTitleRow}><View style={s.needIcon}><Ionicons name={need.icon} size={23} color={Stitch.color.primary}/></View><Text style={s.needTitle}>{need.title}</Text></View><Text numberOfLines={3} style={s.needDescription}>{need.description}</Text><View style={s.divider}/><View style={s.needActions}><View style={s.moreBadge}><Text style={s.moreText}>+3</Text></View><Pressable style={s.amberButton} onPress={()=>router.push(`/need/${need.id}`)}><Text style={s.amberButtonText}>I can help</Text></Pressable></View></Pressable>)}</ScrollView>
  <SectionHeader title="Active Projects"/>
  {activeProjects.map(project=><View key={project.id} style={s.projectCard}><View style={s.cardTop}><View style={s.resourcedBadge}><Ionicons name="flash" size={14} color={Stitch.color.secondary}/><Text style={s.resourcedText}>RESOURCED</Text></View><Text style={s.distanceText}>● Active</Text></View><View style={s.projectBody}><View style={s.projectThumb}><Ionicons name={project.id==='school-001'?'school-outline':'people-outline'} size={30} color={Stitch.color.onSurfaceVariant}/></View><View style={{flex:1}}><Text style={s.sdg}>{project.sdg}</Text><Text style={s.projectTitle}>{project.title}</Text><Text style={s.projectDescription} numberOfLines={2}>{project.description}</Text></View></View><View style={s.progressHead}><Text style={s.progressLabel}>{project.label}</Text><Text style={s.progressValue}>{project.progress}%</Text></View><View style={s.progressTrack}><View style={[s.progressFill,{width:`${project.progress}%` as `${number}%`}]}/></View><View style={s.divider}/><View style={s.projectActions}><Pressable style={s.outlineButton} onPress={()=>router.push(`/project/${project.id}`)}><Text style={s.outlineText}>View Details</Text></Pressable><Pressable style={s.navyButton} onPress={()=>router.push(`/project/${project.id}`)}><Text style={s.navyButtonText}>Join Action</Text></Pressable></View></View>)}
  <View style={s.compass}><Text style={s.eyebrow}>3P ACTION COMPASS</Text><Text style={s.compassTitle}>Respond from where you are and what you can bring.</Text><View style={s.compassRow}>{['Place','Position','Possessions'].map(label=><View key={label} style={s.compassChip}><Text style={s.compassChipText}>{label}</Text></View>)}</View><Pressable style={s.workspaceLink} onPress={()=>router.push('/workspace')}><Text style={s.workspaceText}>Open my role-aware workspace</Text><Ionicons name="arrow-forward" size={18} color={Stitch.color.primary}/></Pressable></View>
 </ScrollView><StitchBottomNav/></View></SafeAreaView>
}
function SectionHeader({title,meta}:{title:string;meta?:string}){return <View style={s.sectionHeader}><Text style={s.sectionTitle}>{title}</Text>{meta&&<Text style={s.sectionMeta}>{meta}</Text>}</View>}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:Stitch.color.background},screen:{flex:1},content:{paddingBottom:Stitch.space.xl},
 searchRow:{paddingHorizontal:Stitch.space.screen,paddingTop:Stitch.space.md,paddingBottom:Stitch.space.sm,flexDirection:'row',gap:Stitch.space.sm,backgroundColor:Stitch.color.surface},searchBox:{flex:1,minHeight:44,flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:Stitch.space.sm,borderWidth:1,borderColor:Stitch.color.outlineVariant,borderRadius:Stitch.radius.md,backgroundColor:Stitch.color.surfaceLowest},searchInput:{flex:1,color:Stitch.color.onSurface,...Stitch.type.body},nearButton:{minHeight:44,paddingHorizontal:Stitch.space.md,flexDirection:'row',alignItems:'center',gap:Stitch.space.xs,borderRadius:Stitch.radius.md,borderWidth:1,borderColor:Stitch.color.outlineVariant,backgroundColor:Stitch.color.surfaceHigh},nearText:{...Stitch.type.tag,color:Stitch.color.primary},
 viewToggle:{marginHorizontal:Stitch.space.screen,marginVertical:Stitch.space.sm,padding:Stitch.space.xs,flexDirection:'row',borderRadius:Stitch.radius.md,backgroundColor:Stitch.color.surfaceLow},toggle:{flex:1,minHeight:34,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:Stitch.space.xs,borderRadius:Stitch.radius.base},toggleOn:{backgroundColor:Stitch.color.primaryContainer},toggleText:{...Stitch.type.tag,color:Stitch.color.onSurfaceVariant},toggleOnText:{...Stitch.type.tag,color:Stitch.color.onPrimaryContainer},
 mapCanvas:{height:270,backgroundColor:'#DDE4E9',overflow:'hidden',borderTopWidth:1,borderBottomWidth:1,borderColor:Stitch.color.outlineVariant,position:'relative',justifyContent:'flex-end'},mapGrid:{...StyleSheet.absoluteFillObject,opacity:.35,borderWidth:18,borderColor:'#C7D0D6'},pin:{position:'absolute',width:46,height:46,borderRadius:23,backgroundColor:Stitch.color.tertiaryFixed,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:Stitch.color.surfaceLowest},pinGreen:{backgroundColor:Stitch.color.secondaryFixed},mapCaption:{backgroundColor:'rgba(0,37,64,.88)',padding:Stitch.space.base,paddingRight:70},mapCaptionTitle:{...Stitch.type.card,color:Stitch.color.onPrimary},mapCaptionText:{...Stitch.type.footnote,color:Stitch.color.primaryFixed},mapAction:{position:'absolute',right:Stitch.space.screen,bottom:Stitch.space.lg,width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:Stitch.color.surfaceLowest,borderWidth:1,borderColor:Stitch.color.outlineVariant},
 syncBanner:{margin:Stitch.space.screen,marginBottom:0,padding:Stitch.space.md,flexDirection:'row',gap:Stitch.space.sm,borderRadius:Stitch.radius.lg,backgroundColor:Stitch.color.tertiaryFixed},syncTitle:{...Stitch.type.bodyBold,color:Stitch.color.tertiary},syncText:{...Stitch.type.footnote,color:Stitch.color.onSurfaceVariant},
 sectionHeader:{paddingHorizontal:Stitch.space.screen,paddingTop:Stitch.space.xl,paddingBottom:Stitch.space.md,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionTitle:{...Stitch.type.headline,color:Stitch.color.onSurface},sectionMeta:{...Stitch.type.tag,color:Stitch.color.primary},horizontalCards:{paddingHorizontal:Stitch.space.screen,gap:Stitch.space.md},needCard:{width:292,padding:Stitch.space.card,borderRadius:Stitch.radius.lg,borderWidth:1,borderColor:Stitch.color.outlineVariant,backgroundColor:Stitch.color.surfaceLowest,gap:Stitch.space.sm},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:Stitch.space.sm},statusBadge:{paddingHorizontal:9,paddingVertical:5,borderRadius:Stitch.radius.full,backgroundColor:Stitch.color.tertiaryFixed,flexDirection:'row',alignItems:'center',gap:4},statusReported:{backgroundColor:Stitch.color.errorContainer},statusText:{...Stitch.type.tag,color:Stitch.color.tertiary},statusReportedText:{color:Stitch.color.error},distance:{flexDirection:'row',alignItems:'center',gap:3},distanceText:{...Stitch.type.footnote,color:Stitch.color.onSurface},needTitleRow:{flexDirection:'row',alignItems:'center',gap:Stitch.space.sm},needIcon:{width:38,height:38,borderRadius:Stitch.radius.base,alignItems:'center',justifyContent:'center',backgroundColor:Stitch.color.tertiaryFixed},needTitle:{flex:1,...Stitch.type.card,color:Stitch.color.onSurface},needDescription:{...Stitch.type.body,color:Stitch.color.onSurfaceVariant},divider:{height:1,backgroundColor:Stitch.color.outlineVariant},needActions:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},moreBadge:{width:25,height:25,borderRadius:13,backgroundColor:Stitch.color.surfaceHigh,alignItems:'center',justifyContent:'center'},moreText:{...Stitch.type.footnote,color:Stitch.color.onSurfaceVariant},amberButton:{minHeight:44,paddingHorizontal:Stitch.space.base,borderRadius:Stitch.radius.md,backgroundColor:Stitch.color.amber,alignItems:'center',justifyContent:'center'},amberButtonText:{...Stitch.type.tag,color:Stitch.color.primary},
 projectCard:{marginHorizontal:Stitch.space.screen,marginBottom:Stitch.space.md,padding:Stitch.space.card,borderRadius:Stitch.radius.lg,borderWidth:1,borderColor:Stitch.color.outlineVariant,backgroundColor:Stitch.color.surfaceLowest,gap:Stitch.space.md},resourcedBadge:{alignSelf:'flex-start',paddingHorizontal:9,paddingVertical:5,borderRadius:Stitch.radius.full,backgroundColor:Stitch.color.secondaryFixed,flexDirection:'row',alignItems:'center',gap:4},resourcedText:{...Stitch.type.tag,color:Stitch.color.secondary},projectBody:{flexDirection:'row',gap:Stitch.space.md},projectThumb:{width:70,height:70,borderRadius:Stitch.radius.md,borderWidth:1,borderColor:Stitch.color.outlineVariant,backgroundColor:Stitch.color.surfaceHigh,alignItems:'center',justifyContent:'center'},sdg:{...Stitch.type.tag,color:Stitch.color.secondary,fontWeight:'900'},projectTitle:{...Stitch.type.card,color:Stitch.color.onSurface,marginTop:2},projectDescription:{...Stitch.type.footnote,color:Stitch.color.onSurfaceVariant,marginTop:3},progressHead:{flexDirection:'row',justifyContent:'space-between'},progressLabel:{...Stitch.type.tag,color:Stitch.color.onSurface},progressValue:{...Stitch.type.tag,color:Stitch.color.primary},progressTrack:{height:8,borderRadius:4,backgroundColor:Stitch.color.surfaceHigh,overflow:'hidden'},progressFill:{height:8,backgroundColor:Stitch.color.secondary},projectActions:{flexDirection:'row',justifyContent:'flex-end',gap:Stitch.space.sm},outlineButton:{minHeight:44,paddingHorizontal:Stitch.space.md,borderWidth:1,borderColor:Stitch.color.outlineVariant,borderRadius:Stitch.radius.md,alignItems:'center',justifyContent:'center'},outlineText:{...Stitch.type.tag,color:Stitch.color.primary},navyButton:{minHeight:44,paddingHorizontal:Stitch.space.md,borderRadius:Stitch.radius.md,backgroundColor:Stitch.color.primaryContainer,alignItems:'center',justifyContent:'center'},navyButtonText:{...Stitch.type.tag,color:Stitch.color.onPrimary},
 compass:{margin:Stitch.space.screen,padding:Stitch.space.lg,borderRadius:Stitch.radius.hero,backgroundColor:Stitch.color.primaryContainer,gap:Stitch.space.md},eyebrow:{...Stitch.type.eyebrow,color:Stitch.color.onPrimaryContainer},compassTitle:{...Stitch.type.headline,color:Stitch.color.onPrimary},compassRow:{flexDirection:'row',gap:Stitch.space.sm},compassChip:{flex:1,paddingVertical:10,borderRadius:Stitch.radius.md,backgroundColor:'rgba(207,229,255,.12)',alignItems:'center'},compassChipText:{...Stitch.type.tag,color:Stitch.color.primaryFixed},workspaceLink:{minHeight:48,paddingHorizontal:Stitch.space.md,borderRadius:Stitch.radius.md,backgroundColor:Stitch.color.surfaceLowest,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},workspaceText:{...Stitch.type.bodyBold,color:Stitch.color.primary}
});