import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { getAccessToken } from '../lib/session';

type Notice={id:string;category:string;title:string;body:string;resourceType?:string;resourceId?:string;readAt?:string;createdAt:string};
type Preferences={inApp:boolean;push:boolean;sms:boolean;email:boolean;updatedAt?:string};
const defaults:Preferences={inApp:true,push:true,sms:false,email:false};

export default function Notifications(){
  const[items,setItems]=useState<Notice[]>([]);const[prefs,setPrefs]=useState<Preferences>(defaults);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  async function auth(){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');const token=await getAccessToken();if(!base){setError('The notification API is not configured on this build.');return null}if(!token){router.replace('/signin');return null}return{base,token}}
  async function load(){const a=await auth();if(!a){setLoading(false);return}setLoading(true);setError('');try{const[n,p]=await Promise.all([fetch(`${a.base}/v1/me/notifications`,{headers:{Authorization:`Bearer ${a.token}`}}),fetch(`${a.base}/v1/me/notification-preferences`,{headers:{Authorization:`Bearer ${a.token}`}})]);if(n.status===401||p.status===401){router.replace('/signin');return}if(!n.ok||!p.ok)throw new Error('load');setItems(await n.json() as Notice[]);setPrefs(await p.json() as Preferences)}catch{setError('Your notifications could not be loaded. Check connectivity and try again.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function save(next:Preferences){setPrefs(next);const a=await auth();if(!a)return;setSaving(true);try{const r=await fetch(`${a.base}/v1/me/notification-preferences`,{method:'PUT',headers:{Authorization:`Bearer ${a.token}`,'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok)throw new Error('save');setPrefs(await r.json() as Preferences)}catch{setError('Your notification preferences could not be saved.')}finally{setSaving(false)}}
  async function read(item:Notice){if(item.readAt)return;const a=await auth();if(!a)return;try{const r=await fetch(`${a.base}/v1/me/notifications/${encodeURIComponent(item.id)}/read`,{method:'POST',headers:{Authorization:`Bearer ${a.token}`}});if(r.ok){const updated=await r.json() as Notice;setItems(v=>v.map(n=>n.id===updated.id?updated:n))}}catch{/* keep unread when offline */}}
  const unread=items.filter(i=>!i.readAt).length;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.eyebrow}>STAY CONNECTED</Text><Text style={styles.title}>Notifications</Text><Text style={styles.intro}>{unread} unread · Keep community action useful without losing control of how you are contacted.</Text>
    <View style={styles.prefCard}><Text style={styles.section}>Delivery preferences</Text><Toggle label="In-app inbox" value={prefs.inApp} disabled={saving} onChange={v=>void save({...prefs,inApp:v})}/><Toggle label="Push notifications" value={prefs.push} disabled={saving} onChange={v=>void save({...prefs,push:v})}/><Toggle label="SMS" value={prefs.sms} disabled={saving} onChange={v=>void save({...prefs,sms:v})}/><Toggle label="Email" value={prefs.email} disabled={saving} onChange={v=>void save({...prefs,email:v})}/><Text style={styles.hint}>External channels are routed through the governed shared notification service and remain subject to consent, suppression and channel policy.</Text></View>
    {loading&&<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading notifications…</Text></View>}{!!error&&<View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={load}><Text style={styles.link}>Try again</Text></Pressable></View>}{!loading&&!error&&items.length===0&&<View style={styles.empty}><Text style={styles.emptyTitle}>Nothing needs your attention</Text><Text style={styles.muted}>Project decisions, verification requests and response milestones will appear here.</Text></View>}{items.map(item=><Pressable key={item.id} style={[styles.card,!item.readAt&&styles.unread]} onPress={()=>void read(item)}><View style={styles.row}><Text style={styles.category}>{human(item.category||'update')}</Text>{!item.readAt&&<View style={styles.dot}/>}</View><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.body}>{item.body}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleString()}</Text></Pressable>)}
  </ScrollView></SafeAreaView>
}
function Toggle({label,value,onChange,disabled}:{label:string;value:boolean;onChange:(v:boolean)=>void;disabled:boolean}){return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} onValueChange={onChange} disabled={disabled}/></View>}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,gap:14,paddingBottom:50},back:{color:'#2D6E9F',fontWeight:'800'},eyebrow:{color:'#2D7A56',fontWeight:'900',letterSpacing:1.5},title:{fontSize:30,lineHeight:36,fontWeight:'900',color:'#17324D'},intro:{color:'#667788',lineHeight:21},prefCard:{backgroundColor:'white',borderRadius:18,padding:16,gap:8},section:{fontSize:18,fontWeight:'900',color:'#17324D',marginBottom:3},toggle:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',minHeight:44},toggleLabel:{color:'#29445C',fontWeight:'700'},hint:{color:'#667788',fontSize:12,lineHeight:17,marginTop:3},center:{alignItems:'center',paddingVertical:24,gap:8},muted:{color:'#667788'},error:{backgroundColor:'#FFF0EF',padding:14,borderRadius:14,gap:6},errorText:{color:'#8A352F',fontWeight:'700'},link:{color:'#2D6E9F',fontWeight:'900'},empty:{backgroundColor:'#EEF3F7',padding:16,borderRadius:16,gap:5},emptyTitle:{fontWeight:'900',color:'#17324D'},card:{backgroundColor:'white',borderRadius:16,padding:15,gap:6,borderWidth:1,borderColor:'transparent'},unread:{borderColor:'#6AA78A',backgroundColor:'#F8FCFA'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},category:{color:'#2D6E9F',fontSize:12,fontWeight:'900'},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#2D7A56'},cardTitle:{color:'#17324D',fontSize:17,fontWeight:'900'},body:{color:'#4E6274',lineHeight:20},time:{color:'#81909C',fontSize:11}});