import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { apiFetch, postJSON } from '../lib/api';

type Pledge={id:string;projectId:string;contributionClass:string;amountMinor:number;currency:string;status:string;createdAt?:string};
export default function MyPledges(){const[items,setItems]=useState<Pledge[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');async function load(){setLoading(true);setError('');try{setItems(await apiFetch<Pledge[]>('/v1/me/funding/pledges'))}catch(e){setError(e instanceof Error?e.message:'Unable to load your pledges.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);async function cancel(id:string){setError('');try{await postJSON(`/v1/funding/pledges/${encodeURIComponent(id)}/cancel`,{});await load()}catch(e){setError(e instanceof Error?e.message:'Pledge could not be cancelled.')}}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.link}>← Workspace</Text></Pressable><Text style={s.kicker}>MY FUNDING COMMITMENTS</Text><Text style={s.title}>Know what you pledged—and what has actually happened.</Text><Text style={s.muted}>A pledge is an auditable commitment, not evidence that money was charged, held or settled. Money movement will remain in the governed PayCore plane when enabled.</Text>{loading&&<ActivityIndicator/>}{!!error&&<View style={s.errorCard}><Text style={s.error}>{error}</Text></View>}{!loading&&items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No funding pledges yet</Text><Text style={s.muted}>Open an Action Project funding plan to make a pledge.</Text></View>:items.map(item=><View key={item.id} style={s.card}><View style={s.row}><Text style={s.amount}>{money(item.amountMinor,item.currency)}</Text><Text style={s.status}>{human(item.status)}</Text></View><Text style={s.project}>Project {item.projectId}</Text><Text style={s.muted}>{human(item.contributionClass)}</Text>{item.status==='pledged'&&<Pressable style={s.secondary} onPress={()=>void cancel(item.id)}><Text style={s.secondaryText}>Cancel open pledge</Text></Pressable>}</View>)}</ScrollView></SafeAreaView>}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function money(minor:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(minor/100)}catch{return `${currency} ${(minor/100).toLocaleString()}`}}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8F5'},content:{padding:20,gap:14,paddingBottom:50},link:{color:'#244D3A',fontWeight:'900'},kicker:{color:'#397355',fontWeight:'900',letterSpacing:1.5},title:{color:'#17352B',fontSize:29,lineHeight:35,fontWeight:'900'},muted:{color:'#67766F',lineHeight:20},card:{backgroundColor:'white',padding:16,borderRadius:18,gap:8},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},amount:{color:'#17352B',fontSize:22,fontWeight:'900'},status:{color:'#285741',fontWeight:'900',backgroundColor:'#E7F1EB',paddingHorizontal:9,paddingVertical:5,borderRadius:999,overflow:'hidden'},project:{color:'#3A5448',fontWeight:'800'},secondary:{borderWidth:1,borderColor:'#8BA495',padding:12,borderRadius:12},secondaryText:{color:'#285741',fontWeight:'900',textAlign:'center'},empty:{backgroundColor:'white',borderRadius:18,padding:16,gap:4},emptyTitle:{color:'#17352B',fontWeight:'900'},errorCard:{backgroundColor:'#FFF0ED',borderRadius:14,padding:13},error:{color:'#913F34',fontWeight:'700'}});
