import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { getAccessToken } from '../lib/session';

type Consent={purpose:string;granted:boolean;policyVersion:string;updatedAt:string};
type PrivacyRequest={id:string;type:string;status:string;requestedAt:string;completedAt?:string};
const policyVersion='2026-08';
const purposes=[
  {id:'impact-research',label:'Impact research',help:'Use de-identified activity to understand which community interventions work.'},
  {id:'product-improvement',label:'Product improvement',help:'Use interaction signals to improve iRespond features and accessibility.'},
];

export default function Privacy(){
  const[consents,setConsents]=useState<Record<string,boolean>>({});const[requests,setRequests]=useState<PrivacyRequest[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[saving,setSaving]=useState('');
  async function auth(){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');const token=await getAccessToken();if(!base){setError('The privacy API is not configured on this build.');return null}if(!token){router.replace('/signin');return null}return{base,token}}
  async function load(){const a=await auth();if(!a){setLoading(false);return}setLoading(true);setError('');try{const[c,r]=await Promise.all([fetch(`${a.base}/v1/me/privacy/consents`,{headers:{Authorization:`Bearer ${a.token}`}}),fetch(`${a.base}/v1/me/privacy/requests`,{headers:{Authorization:`Bearer ${a.token}`}})]);if(c.status===401||r.status===401){router.replace('/signin');return}if(!c.ok||!r.ok)throw new Error('load');const cs=await c.json() as Consent[];setConsents(Object.fromEntries(cs.map(v=>[v.purpose,v.granted])));setRequests(await r.json() as PrivacyRequest[])}catch{setError('Your privacy settings could not be loaded. Check connectivity and try again.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function consent(purpose:string,granted:boolean){const a=await auth();if(!a)return;setSaving(purpose);setConsents(v=>({...v,[purpose]:granted}));try{const r=await fetch(`${a.base}/v1/me/privacy/consents/${encodeURIComponent(purpose)}`,{method:'PUT',headers:{Authorization:`Bearer ${a.token}`,'Content-Type':'application/json'},body:JSON.stringify({granted,policyVersion})});if(!r.ok)throw new Error('save')}catch{setConsents(v=>({...v,[purpose]:!granted}));setError('That consent choice could not be saved.')}finally{setSaving('')}}
  async function request(type:string){const a=await auth();if(!a)return;setSaving(type);try{const r=await fetch(`${a.base}/v1/me/privacy/requests`,{method:'POST',headers:{Authorization:`Bearer ${a.token}`,'Content-Type':'application/json'},body:JSON.stringify({type})});if(!r.ok)throw new Error('request');const created=await r.json() as PrivacyRequest;setRequests(v=>[created,...v]);Alert.alert('Request received','Your request is recorded and auditable. Destructive requests are not executed instantly; privacy operations must validate and fulfill them safely.')}catch{setError('Your privacy request could not be recorded.')}finally{setSaving('')}}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.eyebrow}>PRIVACY & DIGNITY</Text><Text style={styles.title}>Your data, your choices</Text><Text style={styles.intro}>Control optional data uses and exercise access, export, correction or deletion rights. Community impact never requires surrendering unnecessary privacy.</Text>
  {loading&&<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading privacy choices…</Text></View>}{!!error&&<View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={load}><Text style={styles.link}>Try again</Text></Pressable></View>}
  {!loading&&<View style={styles.card}><Text style={styles.section}>Optional data uses</Text>{purposes.map(p=><View key={p.id} style={styles.purpose}><View style={styles.purposeText}><Text style={styles.label}>{p.label}</Text><Text style={styles.help}>{p.help}</Text></View><Switch value={!!consents[p.id]} disabled={saving===p.id} onValueChange={v=>void consent(p.id,v)}/></View>)}<Text style={styles.note}>Required processing for security, legal obligations and core service delivery is governed separately and is not represented as optional consent.</Text></View>}
  <View style={styles.card}><Text style={styles.section}>Data rights</Text><Text style={styles.help}>Create an auditable request. iRespond records the request immediately; fulfillment follows identity, legal, safeguarding and retention checks.</Text><View style={styles.actions}>{['access','export','correction','deletion'].map(t=><Pressable key={t} disabled={!!saving} style={[styles.action,t==='deletion'&&styles.danger]} onPress={()=>void request(t)}><Text style={[styles.actionText,t==='deletion'&&styles.dangerText]}>{human(t)}</Text></Pressable>)}</View></View>
  <View style={styles.card}><Text style={styles.section}>Request history</Text>{requests.length===0?<Text style={styles.muted}>No privacy requests yet.</Text>:requests.map(r=><View key={r.id} style={styles.request}><View><Text style={styles.label}>{human(r.type)}</Text><Text style={styles.help}>{new Date(r.requestedAt).toLocaleString()}</Text></View><Text style={styles.status}>{human(r.status)}</Text></View>)}</View>
  </ScrollView></SafeAreaView>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,gap:14,paddingBottom:50},back:{color:'#2D6E9F',fontWeight:'800'},eyebrow:{color:'#2D7A56',fontWeight:'900',letterSpacing:1.5},title:{fontSize:30,lineHeight:36,fontWeight:'900',color:'#17324D'},intro:{color:'#667788',lineHeight:21},center:{alignItems:'center',paddingVertical:24,gap:8},muted:{color:'#667788'},error:{backgroundColor:'#FFF0EF',padding:14,borderRadius:14,gap:6},errorText:{color:'#8A352F',fontWeight:'700'},link:{color:'#2D6E9F',fontWeight:'900'},card:{backgroundColor:'white',borderRadius:18,padding:16,gap:12},section:{fontSize:18,fontWeight:'900',color:'#17324D'},purpose:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:5},purposeText:{flex:1,gap:3},label:{color:'#29445C',fontWeight:'800'},help:{color:'#667788',lineHeight:18},note:{color:'#7A8792',fontSize:12,lineHeight:17},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{borderWidth:1,borderColor:'#8DA8BA',paddingHorizontal:12,paddingVertical:10,borderRadius:12},actionText:{color:'#275A7D',fontWeight:'900'},danger:{borderColor:'#D5A19C',backgroundColor:'#FFF8F7'},dangerText:{color:'#8A352F'},request:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderTopWidth:1,borderTopColor:'#EDF1F4',paddingTop:10},status:{color:'#2D7A56',fontWeight:'900',fontSize:12}});