import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiFetch, getSession, postJSON, putJSON, type Session } from '../lib/api';

type ProjectDetail = { project: { id:string; title:string; description:string; status:string; createdBy?:string; projectManagerId?:string }; milestones: {id:string;title:string;status:string;sequence:number}[]; contributionNeeds: {id:string;kind:string;description:string;status:string}[] };
type Offer = { id:string; contributionNeedId?:string; contributorId:string; note?:string; availabilityNote?:string; status?:string; state?:string };
type Pledge = { id:string; contributorId:string; contributionClass:string; amountMinor:number; currency:string; status:string };
type FundingPlan = { projectId:string; currency:string; targetMinor:number; communityCounterpartMinor:number; externalTargetMinor:number; status:string; pledgedMinor:number; confirmedMinor:number };

export default function ProjectAdmin() {
  const [session,setSession]=useState<Session|null>(null); const [projectId,setProjectId]=useState(''); const [detail,setDetail]=useState<ProjectDetail|null>(null); const [offers,setOffers]=useState<Offer[]>([]); const [pledges,setPledges]=useState<Pledge[]>([]); const [funding,setFunding]=useState<FundingPlan|null>(null); const [busy,setBusy]=useState('session'); const [error,setError]=useState('');
  const [milestoneTitle,setMilestoneTitle]=useState(''); const [milestoneDescription,setMilestoneDescription]=useState(''); const [sequence,setSequence]=useState('1'); const [projectState,setProjectState]=useState('planning');
  const [contributionKind,setContributionKind]=useState('time'); const [contributionDescription,setContributionDescription]=useState(''); const [quantityNote,setQuantityNote]=useState('');
  const [inviteActor,setInviteActor]=useState(''); const [inviteRole,setInviteRole]=useState('volunteer_lead');
  const [currency,setCurrency]=useState('NGN'); const [target,setTarget]=useState(''); const [counterpart,setCounterpart]=useState('');

  useEffect(()=>{getSession().then(setSession).catch(()=>router.replace('/signin')).finally(()=>setBusy(''))},[]);

  async function load() { if(!projectId.trim())return;setBusy('load');setError('');try{const id=encodeURIComponent(projectId.trim());const d=await apiFetch<ProjectDetail>(`/v1/projects/${id}`,{},false);setDetail(d);setProjectState(d.project.status);await Promise.all([loadOffers(id),loadFunding(id)]);}catch(e){setDetail(null);setError(message(e));}finally{setBusy('')}}
  async function loadOffers(id=encodeURIComponent(projectId.trim())) { try{setOffers(await apiFetch<Offer[]>(`/v1/projects/${id}/contribution-offers`));}catch(e){if(status(e)!==403)setError(message(e));else setOffers([])} }
  async function loadFunding(id=encodeURIComponent(projectId.trim())) { try{const plan=await apiFetch<FundingPlan>(`/v1/projects/${id}/funding`);setFunding(plan);setCurrency(plan.currency);setTarget(String(plan.targetMinor/100));setCounterpart(String(plan.communityCounterpartMinor/100));try{setPledges(await apiFetch<Pledge[]>(`/v1/projects/${id}/funding/pledges`));}catch(e){if(status(e)!==403)throw e;setPledges([])}}catch(e){if(status(e)===404){setFunding(null);setPledges([])}else setError(message(e))} }

  async function addMilestone(){if(!detail||!milestoneTitle.trim())return;setBusy('milestone');try{await postJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/milestones`,{title:milestoneTitle.trim(),description:milestoneDescription.trim(),sequence:Number(sequence)||1,targetAt:null});setMilestoneTitle('');setMilestoneDescription('');await load();}catch(e){setError(message(e))}finally{setBusy('')}}
  async function transitionProject(){if(!detail)return;setBusy('transition');try{await postJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/transition`,{state:projectState});await load();}catch(e){setError(message(e))}finally{setBusy('')}}
  async function addContributionNeed(){if(!detail||!contributionDescription.trim())return;setBusy('need');try{await postJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/contribution-needs`,{kind:contributionKind.trim(),description:contributionDescription.trim(),quantityNote:quantityNote.trim()});setContributionDescription('');setQuantityNote('');await load();}catch(e){setError(message(e))}finally{setBusy('')}}
  async function invite(){if(!detail||!inviteActor.trim()||!inviteRole.trim())return;setBusy('invite');try{await postJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/roles/invite`,{actorId:inviteActor.trim(),role:inviteRole.trim()});setInviteActor('');Alert.alert('Role invitation created','The invited identity must explicitly accept it.');}catch(e){setError(message(e))}finally{setBusy('')}}
  async function decideOffer(offerId:string,decision:'accepted'|'declined'){if(!detail)return;setBusy(offerId);try{await postJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/contribution-offers/${encodeURIComponent(offerId)}/decision`,{decision,closeNeed:false});await loadOffers();}catch(e){setError(message(e))}finally{setBusy('')}}
  async function fulfillOffer(offerId:string){if(!detail)return;setBusy(offerId);try{await postJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/contribution-offers/${encodeURIComponent(offerId)}/fulfill`,{});await loadOffers();}catch(e){setError(message(e))}finally{setBusy('')}}
  async function saveFunding(){if(!detail)return;const total=Number(target),community=Number(counterpart);if(!Number.isFinite(total)||!Number.isFinite(community)||total<=0||community<0||community>total){Alert.alert('Check funding plan','Use positive amounts and keep counterpart within the total.');return}setBusy('funding');try{await putJSON(`/v1/projects/${encodeURIComponent(detail.project.id)}/funding`,{currency:currency.trim().toUpperCase(),targetMinor:Math.round(total*100),communityCounterpartMinor:Math.round(community*100)});await loadFunding();}catch(e){setError(message(e))}finally{setBusy('')}}

  if(busy==='session')return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Loading project authority…</Text></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.link}>← Workspace</Text></Pressable><Text style={s.meta}>{session?.subject}</Text></View><Text style={s.kicker}>PROJECT STEWARDSHIP</Text><Text style={s.title}>Turn verified needs into governed delivery.</Text><Text style={s.muted}>These controls call the real project, contribution and funding APIs. Project-specific roles are re-evaluated by the server on every action.</Text>{!!error&&<View style={s.errorCard}><Text style={s.error}>{error}</Text></View>}
  <View style={s.card}><Text style={s.section}>Open a Project Room</Text><TextInput style={s.input} value={projectId} onChangeText={setProjectId} autoCapitalize="none" placeholder="Project ID"/><Pressable style={s.secondary} onPress={()=>void load()}><Text style={s.secondaryText}>{busy==='load'?'Loading…':'Load stewardship controls'}</Text></Pressable></View>
  {detail&&<><View style={s.hero}><Text style={s.heroKicker}>{human(detail.project.status)}</Text><Text style={s.heroTitle}>{detail.project.title}</Text><Text style={s.heroBody}>{detail.project.description}</Text></View>
  <View style={s.card}><Text style={s.section}>Project lifecycle</Text><TextInput style={s.input} value={projectState} onChangeText={setProjectState} placeholder="Next project state"/><Pressable style={s.primary} onPress={()=>void transitionProject()}><Text style={s.primaryText}>Apply project transition</Text></Pressable><Text style={s.note}>The server rejects invalid lifecycle jumps even when typed manually.</Text></View>
  <View style={s.card}><Text style={s.section}>Milestones</Text>{detail.milestones.map(m=><View key={m.id} style={s.listRow}><View style={{flex:1}}><Text style={s.itemTitle}>{m.sequence}. {m.title}</Text><Text style={s.note}>{human(m.status)}</Text></View><Text style={s.meta}>{m.id}</Text></View>)}<TextInput style={s.input} value={milestoneTitle} onChangeText={setMilestoneTitle} placeholder="Milestone title"/><TextInput style={s.input} value={milestoneDescription} onChangeText={setMilestoneDescription} placeholder="Description"/><TextInput style={s.input} value={sequence} onChangeText={setSequence} keyboardType="number-pad" placeholder="Sequence"/><Pressable style={s.secondary} onPress={()=>void addMilestone()}><Text style={s.secondaryText}>Add milestone</Text></Pressable></View>
  <View style={s.card}><Text style={s.section}>Contribution needs</Text>{detail.contributionNeeds.map(n=><View key={n.id} style={s.listRow}><View style={{flex:1}}><Text style={s.itemTitle}>{human(n.kind)} · {n.description}</Text><Text style={s.note}>{human(n.status)}</Text></View></View>)}<TextInput style={s.input} value={contributionKind} onChangeText={setContributionKind} placeholder="Kind: time, skills, materials…"/><TextInput style={s.input} value={contributionDescription} onChangeText={setContributionDescription} placeholder="What is needed?"/><TextInput style={s.input} value={quantityNote} onChangeText={setQuantityNote} placeholder="Quantity / availability note"/><Pressable style={s.secondary} onPress={()=>void addContributionNeed()}><Text style={s.secondaryText}>Publish contribution need</Text></Pressable></View>
  <View style={s.card}><Text style={s.section}>Contribution offers</Text>{offers.length===0?<Text style={s.muted}>No reviewable offers, or this identity is not a contribution steward.</Text>:offers.map(o=><View key={o.id} style={s.offer}><Text style={s.itemTitle}>{o.contributorId}</Text>{!!o.note&&<Text style={s.muted}>{o.note}</Text>}<Text style={s.note}>{human(o.status??o.state??'offered')}</Text><View style={s.actions}><Pressable style={s.action} onPress={()=>void decideOffer(o.id,'accepted')}><Text style={s.actionText}>Accept</Text></Pressable><Pressable style={s.action} onPress={()=>void decideOffer(o.id,'declined')}><Text style={s.actionText}>Decline</Text></Pressable><Pressable style={s.action} onPress={()=>void fulfillOffer(o.id)}><Text style={s.actionText}>Mark fulfilled</Text></Pressable></View></View>)}</View>
  <View style={s.card}><Text style={s.section}>Project roles</Text><TextInput style={s.input} value={inviteActor} onChangeText={setInviteActor} autoCapitalize="none" placeholder="Actor / identity ID"/><TextInput style={s.input} value={inviteRole} onChangeText={setInviteRole} autoCapitalize="none" placeholder="project_manager, verifier, volunteer_lead…"/><Pressable style={s.secondary} onPress={()=>void invite()}><Text style={s.secondaryText}>Invite project role</Text></Pressable></View>
  <View style={s.card}><Text style={s.section}>Funding & counterpart plan</Text>{funding&&<View style={s.funding}><Text style={s.amount}>{money(funding.pledgedMinor,funding.currency)} pledged</Text><Text style={s.note}>{money(funding.confirmedMinor,funding.currency)} externally confirmed · target {money(funding.targetMinor,funding.currency)}</Text></View>}<TextInput style={s.input} value={currency} onChangeText={setCurrency} maxLength={3} autoCapitalize="characters" placeholder="Currency"/><TextInput style={s.input} value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder="Total target"/><TextInput style={s.input} value={counterpart} onChangeText={setCounterpart} keyboardType="decimal-pad" placeholder="Community counterpart"/><Pressable style={s.primary} onPress={()=>void saveFunding()}><Text style={s.primaryText}>Publish funding plan</Text></Pressable>{pledges.map(p=><View key={p.id} style={s.listRow}><Text style={s.itemTitle}>{p.contributorId}</Text><Text style={s.note}>{money(p.amountMinor,p.currency)} · {human(p.status)}</Text></View>)}<Text style={s.note}>Pledges are commitments only; this screen does not claim payment settlement.</Text></View>
  </>}
  </ScrollView></SafeAreaView>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function message(e:unknown){return e instanceof Error?e.message:'Request failed.'}function status(e:unknown){return typeof e==='object'&&e&&'status'in e?Number((e as{status?:unknown}).status):0}function money(minor:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(minor/100)}catch{return `${currency} ${(minor/100).toLocaleString()}`}}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8F5'},content:{padding:20,gap:14,paddingBottom:55},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},top:{flexDirection:'row',justifyContent:'space-between',gap:10},link:{color:'#244D3A',fontWeight:'900'},meta:{color:'#829087',fontSize:11},kicker:{color:'#397355',fontWeight:'900',letterSpacing:1.5},title:{color:'#17352B',fontSize:29,lineHeight:35,fontWeight:'900'},muted:{color:'#67766F',lineHeight:20},hero:{backgroundColor:'#173F2F',borderRadius:20,padding:18,gap:6},heroKicker:{color:'#A7D8BE',fontWeight:'900',fontSize:11,letterSpacing:1.2},heroTitle:{color:'white',fontSize:23,fontWeight:'900'},heroBody:{color:'#DCEAE3',lineHeight:20},card:{backgroundColor:'white',borderRadius:18,padding:16,gap:10},section:{color:'#17352B',fontSize:18,fontWeight:'900'},input:{borderWidth:1,borderColor:'#D5DED8',borderRadius:12,padding:12,backgroundColor:'#FCFDFC'},primary:{backgroundColor:'#173F2F',padding:14,borderRadius:13},primaryText:{color:'white',textAlign:'center',fontWeight:'900'},secondary:{borderWidth:1,borderColor:'#8BA495',padding:13,borderRadius:13},secondaryText:{color:'#285741',fontWeight:'900',textAlign:'center'},note:{color:'#7C8881',fontSize:12,lineHeight:17},listRow:{borderTopWidth:1,borderTopColor:'#EEF1EF',paddingTop:9,gap:3},itemTitle:{color:'#274338',fontWeight:'800'},offer:{backgroundColor:'#F7F9F7',borderRadius:13,padding:12,gap:6},actions:{flexDirection:'row',flexWrap:'wrap',gap:7},action:{borderWidth:1,borderColor:'#A1B2A8',borderRadius:99,paddingHorizontal:10,paddingVertical:8},actionText:{color:'#285741',fontWeight:'800',fontSize:12},funding:{backgroundColor:'#E7F1EB',borderRadius:14,padding:13,gap:3},amount:{color:'#24543E',fontSize:18,fontWeight:'900'},errorCard:{backgroundColor:'#FFF0ED',borderRadius:14,padding:13},error:{color:'#913F34',fontWeight:'700'}});
