import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiFetch, postJSON } from '../lib/api';

type Report={id:string;subjectType:string;subjectId:string;reason:string;details?:string;status:string;createdAt?:string};
export default function SafetyCenter(){const[items,setItems]=useState<Report[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[appeals,setAppeals]=useState<Record<string,string>>({});async function load(){setLoading(true);setError('');try{setItems(await apiFetch<Report[]>('/v1/me/safety/reports'))}catch(e){setError(e instanceof Error?e.message:'Unable to load your safety reports.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);async function appeal(id:string){const reason=(appeals[id]??'').trim();if(!reason){Alert.alert('Appeal reason required','Explain why you believe the decision should be reviewed.');return}try{await postJSON(`/v1/safety/reports/${encodeURIComponent(id)}/appeal`,{reason});setAppeals(v=>({...v,[id]:''}));Alert.alert('Appeal recorded','Your appeal has been added to the auditable safety workflow.');await load()}catch(e){setError(e instanceof Error?e.message:'Appeal could not be recorded.')}}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.link}>← Workspace</Text></Pressable><Text style={s.kicker}>SAFETY & APPEALS</Text><Text style={s.title}>Confidential reporting with a visible follow-up trail.</Text><Text style={s.muted}>Use iRespond for platform safety concerns. If someone is in immediate danger, contact appropriate local emergency or safeguarding services.</Text><Pressable style={s.primary} onPress={()=>router.push({pathname:'/report-safety',params:{subjectType:'platform',subjectId:'general'}})}><Text style={s.primaryText}>Report a safety concern</Text></Pressable>{loading&&<ActivityIndicator/>}{!!error&&<View style={s.errorCard}><Text style={s.error}>{error}</Text></View>}<Text style={s.section}>Your reports</Text>{!loading&&items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No reports submitted</Text><Text style={s.muted}>Reports you create will appear here without becoming public content.</Text></View>:items.map(item=><View key={item.id} style={s.card}><View style={s.row}><Text style={s.badge}>{human(item.reason)}</Text><Text style={s.status}>{human(item.status)}</Text></View><Text style={s.itemTitle}>{human(item.subjectType)} · {item.subjectId}</Text>{!!item.details&&<Text style={s.muted}>{item.details}</Text>}<TextInput style={s.input} value={appeals[item.id]??''} onChangeText={value=>setAppeals(v=>({...v,[item.id]:value}))} placeholder="Appeal reason, if a review is needed" multiline/><Pressable style={s.secondary} onPress={()=>void appeal(item.id)}><Text style={s.secondaryText}>Submit appeal</Text></Pressable></View>)}</ScrollView></SafeAreaView>}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FBF7F5'},content:{padding:20,gap:14,paddingBottom:50},link:{color:'#74443D',fontWeight:'900'},kicker:{color:'#9A5147',fontWeight:'900',letterSpacing:1.5},title:{color:'#422E2A',fontSize:29,lineHeight:35,fontWeight:'900'},muted:{color:'#786B67',lineHeight:20},primary:{backgroundColor:'#7F3E38',padding:15,borderRadius:14},primaryText:{color:'white',fontWeight:'900',textAlign:'center'},section:{color:'#422E2A',fontSize:19,fontWeight:'900'},card:{backgroundColor:'white',borderRadius:18,padding:16,gap:9},row:{flexDirection:'row',justifyContent:'space-between',gap:10},badge:{color:'#8A3F36',fontWeight:'900',backgroundColor:'#FFF0ED',paddingHorizontal:9,paddingVertical:5,borderRadius:999,overflow:'hidden'},status:{color:'#725E59',fontWeight:'800',fontSize:12},itemTitle:{color:'#422E2A',fontSize:17,fontWeight:'900'},input:{borderWidth:1,borderColor:'#DFCFCB',borderRadius:12,padding:12,minHeight:72,textAlignVertical:'top'},secondary:{borderWidth:1,borderColor:'#C5AAA4',padding:12,borderRadius:12},secondaryText:{color:'#74443D',fontWeight:'900',textAlign:'center'},empty:{backgroundColor:'white',borderRadius:18,padding:16,gap:4},emptyTitle:{color:'#422E2A',fontWeight:'900'},errorCard:{backgroundColor:'#FFEDE9',padding:13,borderRadius:13},error:{color:'#913F34',fontWeight:'700'}});
