import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiFetch, getSession, postJSON } from '../lib/api';
import { hasCapability } from '../lib/capabilities';

type SafetyReport = { id:string; reporterId?:string; subjectType:string; subjectId:string; reason:string; details?:string; status:string; createdAt?:string };

export default function SafetyOperations(){
  const[items,setItems]=useState<SafetyReport[]>([]);const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[error,setError]=useState('');const[note,setNote]=useState<Record<string,string>>({});
  async function load(){setLoading(true);setError('');try{const session=await getSession();const ok=hasCapability(session.roles,'safety.review');setAuthorized(ok);if(!ok)return;setItems(await apiFetch<SafetyReport[]>('/v1/safety/review-queue'));}catch(e){setError(e instanceof Error?e.message:'Unable to load safety queue.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function decide(id:string,decision:'triage'|'action'|'dismiss'|'close'){setError('');try{await postJSON(`/v1/safety/reports/${encodeURIComponent(id)}/decision`,{decision,note:note[id]??''});await load()}catch(e){setError(e instanceof Error?e.message:'Decision could not be recorded.')}}
  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Loading confidential review queue…</Text></View></SafeAreaView>;
  if(!authorized)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.kicker}>TRUST & SAFETY</Text><Text style={s.title}>Reviewer authority required.</Text><Text style={s.muted}>This queue is restricted to safety reviewers and trust-and-safety administrators.</Text><Pressable onPress={()=>router.back()}><Text style={s.link}>Back</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.link}>← Workspace</Text></Pressable><Pressable onPress={()=>void load()}><Text style={s.link}>Refresh</Text></Pressable></View><Text style={s.kicker}>TRUST & SAFETY OPERATIONS</Text><Text style={s.title}>Review confidential concerns with an auditable decision trail.</Text><Text style={s.muted}>Reports are not public posts. Decisions do not erase appeal rights, and immediate-danger situations still belong with appropriate local emergency or safeguarding services.</Text>{!!error&&<View style={s.errorCard}><Text style={s.error}>{error}</Text></View>}{items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Queue clear</Text><Text style={s.muted}>No safety reports are waiting in the current review queue.</Text></View>:items.map(item=><View key={item.id} style={s.card}><View style={s.row}><Text style={s.badge}>{human(item.reason)}</Text><Text style={s.status}>{human(item.status)}</Text></View><Text style={s.itemTitle}>{human(item.subjectType)} · {item.subjectId}</Text>{!!item.details&&<Text style={s.muted}>{item.details}</Text>}<TextInput style={s.input} value={note[item.id]??''} onChangeText={v=>setNote(current=>({...current,[item.id]:v}))} placeholder="Reviewer note (auditable)" multiline/><View style={s.actions}>{(['triage','action','dismiss','close'] as const).map(decision=><Pressable key={decision} style={[s.action,decision==='action'&&s.actionStrong]} onPress={()=>void decide(item.id,decision)}><Text style={[s.actionText,decision==='action'&&s.actionStrongText]}>{human(decision)}</Text></Pressable>)}</View></View>)}</ScrollView></SafeAreaView>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FBF7F5'},content:{padding:20,gap:14,paddingBottom:50},center:{flex:1,justifyContent:'center',alignItems:'center',gap:12,padding:24},top:{flexDirection:'row',justifyContent:'space-between'},link:{color:'#74443D',fontWeight:'900'},kicker:{color:'#9A5147',fontWeight:'900',letterSpacing:1.5},title:{color:'#422E2A',fontSize:29,lineHeight:35,fontWeight:'900'},muted:{color:'#786B67',lineHeight:20},empty:{backgroundColor:'white',padding:18,borderRadius:18,gap:4},emptyTitle:{color:'#422E2A',fontWeight:'900',fontSize:18},card:{backgroundColor:'white',padding:16,borderRadius:18,gap:10},row:{flexDirection:'row',justifyContent:'space-between',gap:10},badge:{color:'#8A3F36',fontWeight:'900',backgroundColor:'#FFF0ED',paddingHorizontal:9,paddingVertical:5,borderRadius:999,overflow:'hidden'},status:{color:'#725E59',fontWeight:'800',fontSize:12},itemTitle:{color:'#422E2A',fontSize:18,fontWeight:'900'},input:{borderWidth:1,borderColor:'#DFCFCB',borderRadius:12,padding:12,minHeight:72,textAlignVertical:'top'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{borderWidth:1,borderColor:'#C5AAA4',paddingHorizontal:12,paddingVertical:9,borderRadius:99},actionText:{color:'#74443D',fontWeight:'800'},actionStrong:{backgroundColor:'#7F3E38',borderColor:'#7F3E38'},actionStrongText:{color:'white'},errorCard:{backgroundColor:'#FFEDE9',padding:13,borderRadius:13},error:{color:'#913F34',fontWeight:'700'}});
