package safety

import(
 "context";"crypto/rand";"encoding/hex";"encoding/json";"errors";"fmt";"strings";"time"
 "github.com/jackc/pgx/v5";"github.com/jackc/pgx/v5/pgxpool"
)

type Service struct{pool *pgxpool.Pool}
type Report struct{ID string `json:"id"`;ReporterID string `json:"-"`;SubjectType string `json:"subjectType"`;SubjectID string `json:"subjectId"`;Reason string `json:"reason"`;Details string `json:"details"`;Severity string `json:"severity"`;Status string `json:"status"`;CreatedAt time.Time `json:"createdAt"`;UpdatedAt time.Time `json:"updatedAt"`}
type Appeal struct{ID string `json:"id"`;ReportID string `json:"reportId"`;Reason string `json:"reason"`;Status string `json:"status"`;CreatedAt time.Time `json:"createdAt"`}
var ErrInvalid=errors.New("invalid safety report");var ErrNotFound=errors.New("safety report not found")
var subjects=map[string]bool{"need":true,"evidence":true,"project":true,"contribution":true,"profile":true,"platform":true};var reasons=map[string]bool{"fraud":true,"privacy":true,"harassment":true,"hate":true,"unsafe_activity":true,"child_safety":true,"misinformation":true,"financial_abuse":true,"other":true}
func New(ctx context.Context,url string)(*Service,error){p,e:=pgxpool.New(ctx,url);if e!=nil{return nil,e};if e=p.Ping(ctx);e!=nil{p.Close();return nil,fmt.Errorf("safety yugabytedb ping: %w",e)};return &Service{p},nil}
func(s *Service)Close(){if s!=nil&&s.pool!=nil{s.pool.Close()}}
func(s *Service)Create(ctx context.Context,reporter,subjectType,subjectID,reason,details string)(Report,error){subjectType=strings.TrimSpace(subjectType);reason=strings.TrimSpace(reason);subjectID=strings.TrimSpace(subjectID);details=strings.TrimSpace(details);if !subjects[subjectType]||!reasons[reason]||subjectID==""||len(details)>4000{return Report{},ErrInvalid};severity:="standard";if reason=="child_safety"||reason=="financial_abuse"{severity="high"};r:=Report{ID:newID(),ReporterID:reporter,SubjectType:subjectType,SubjectID:subjectID,Reason:reason,Details:details,Severity:severity,Status:"submitted",CreatedAt:time.Now().UTC()};r.UpdatedAt=r.CreatedAt;tx,e:=s.pool.BeginTx(ctx,pgx.TxOptions{});if e!=nil{return Report{},e};defer tx.Rollback(ctx);_,e=tx.Exec(ctx,`INSERT INTO safety_reports(id,reporter_id,subject_type,subject_id,reason,details,severity,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)`,r.ID,reporter,subjectType,subjectID,reason,details,severity,r.Status,r.CreatedAt);if e!=nil{return Report{},e};payload,_:=json.Marshal(map[string]any{"reportId":r.ID,"subjectType":subjectType,"subjectId":subjectID,"reason":reason,"severity":severity});_,e=tx.Exec(ctx,`INSERT INTO outbox_events(id,aggregate_type,aggregate_id,event_type,payload) VALUES($1,'safety_report',$2,'safety.reported',$3)`,newID(),r.ID,payload);if e!=nil{return Report{},e};if e=tx.Commit(ctx);e!=nil{return Report{},e};return r,nil}
func(s *Service)Mine(ctx context.Context,user string)([]Report,error){rows,e:=s.pool.Query(ctx,`SELECT id,reporter_id,subject_type,subject_id,reason,details,severity,status,created_at,updated_at FROM safety_reports WHERE reporter_id=$1 ORDER BY created_at DESC`,user);if e!=nil{return nil,e};defer rows.Close();return scan(rows)}
func(s *Service)Queue(ctx context.Context)([]Report,error){rows,e:=s.pool.Query(ctx,`SELECT id,reporter_id,subject_type,subject_id,reason,details,severity,status,created_at,updated_at FROM safety_reports WHERE status IN ('submitted','triaged','appealed') ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,created_at`,);if e!=nil{return nil,e};defer rows.Close();return scan(rows)}
func(s *Service)Decide(ctx context.Context,id,reviewer,decision,note string)(Report,error){next:=map[string]string{"triage":"triaged","action":"actioned","dismiss":"dismissed","close":"closed"}[decision];if next==""{return Report{},ErrInvalid};tx,e:=s.pool.BeginTx(ctx,pgx.TxOptions{});if e!=nil{return Report{},e};defer tx.Rollback(ctx);var r Report;e=tx.QueryRow(ctx,`UPDATE safety_reports SET status=$2,updated_at=now() WHERE id=$1 RETURNING id,reporter_id,subject_type,subject_id,reason,details,severity,status,created_at,updated_at`,id,next).Scan(&r.ID,&r.ReporterID,&r.SubjectType,&r.SubjectID,&r.Reason,&r.Details,&r.Severity,&r.Status,&r.CreatedAt,&r.UpdatedAt);if errors.Is(e,pgx.ErrNoRows){return Report{},ErrNotFound};if e!=nil{return Report{},e};_,e=tx.Exec(ctx,`INSERT INTO safety_decisions(id,report_id,reviewer_id,decision,note) VALUES($1,$2,$3,$4,$5)`,newID(),id,reviewer,decision,strings.TrimSpace(note));if e!=nil{return Report{},e};payload,_:=json.Marshal(map[string]any{"reportId":id,"decision":decision,"status":next,"reviewerId":reviewer});_,e=tx.Exec(ctx,`INSERT INTO outbox_events(id,aggregate_type,aggregate_id,event_type,payload) VALUES($1,'safety_report',$2,'safety.decision_recorded',$3)`,newID(),id,payload);if e!=nil{return Report{},e};if e=tx.Commit(ctx);e!=nil{return Report{},e};return r,nil}
func(s *Service)Appeal(ctx context.Context,id,user,why string)(Appeal,error){why=strings.TrimSpace(why);if why==""||len(why)>4000{return Appeal{},ErrInvalid};tx,e:=s.pool.BeginTx(ctx,pgx.TxOptions{});if e!=nil{return Appeal{},e};defer tx.Rollback(ctx);var exists bool;e=tx.QueryRow(ctx,`SELECT EXISTS(SELECT 1 FROM safety_reports WHERE id=$1)`,id).Scan(&exists);if e!=nil{return Appeal{},e};if !exists{return Appeal{},ErrNotFound};a:=Appeal{ID:newID(),ReportID:id,Reason:why,Status:"submitted",CreatedAt:time.Now().UTC()};_,e=tx.Exec(ctx,`INSERT INTO safety_appeals(id,report_id,appellant_id,reason,status,created_at,updated_at) VALUES($1,$2,$3,$4,'submitted',$5,$5)`,a.ID,id,user,why,a.CreatedAt);if e!=nil{return Appeal{},e};_,e=tx.Exec(ctx,`UPDATE safety_reports SET status='appealed',updated_at=now() WHERE id=$1`,id);if e!=nil{return Appeal{},e};payload,_:=json.Marshal(map[string]any{"reportId":id,"appealId":a.ID});_,e=tx.Exec(ctx,`INSERT INTO outbox_events(id,aggregate_type,aggregate_id,event_type,payload) VALUES($1,'safety_report',$2,'safety.appealed',$3)`,newID(),id,payload);if e!=nil{return Appeal{},e};if e=tx.Commit(ctx);e!=nil{return Appeal{},e};return a,nil}
type scanner interface{Next()bool;Scan(...any)error;Err()error};func scan(rows scanner)([]Report,error){out:=[]Report{};for rows.Next(){var r Report;if e:=rows.Scan(&r.ID,&r.ReporterID,&r.SubjectType,&r.SubjectID,&r.Reason,&r.Details,&r.Severity,&r.Status,&r.CreatedAt,&r.UpdatedAt);e!=nil{return nil,e};out=append(out,r)};return out,rows.Err()}
func newID()string{var b[12]byte;_,_=rand.Read(b[:]);return hex.EncodeToString(b[:])}
