package main

import(
 "context";"encoding/json";"errors";"log";"net/http";"os";"strings"
 "github.com/Atlasfsp/iRespond/services/api/internal/auth"
 "github.com/Atlasfsp/iRespond/services/api/internal/safety"
)
func registerSafetyRoutes(mux *http.ServeMux,identity auth.Verifier)func(){db:=strings.TrimSpace(os.Getenv("DATABASE_URL"));var svc *safety.Service;if db!=""{var e error;svc,e=safety.New(context.Background(),db);if e!=nil{log.Fatalf("initialize safety service: %v",e)}};available:=func(w http.ResponseWriter)bool{if svc==nil{writeJSON(w,503,map[string]string{"error":"trust and safety is not configured"});return false};return true}
 mux.HandleFunc("POST /v1/safety/reports",func(w http.ResponseWriter,r *http.Request){if !available(w){return};p,ok:=authenticate(w,r,identity);if !ok{return};var in struct{SubjectType string `json:"subjectType"`;SubjectID string `json:"subjectId"`;Reason string `json:"reason"`;Details string `json:"details"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid safety report"});return};out,e:=svc.Create(r.Context(),p.Subject,in.SubjectType,in.SubjectID,in.Reason,in.Details);if errors.Is(e,safety.ErrInvalid){writeJSON(w,400,map[string]string{"error":"invalid subject, reason, or details"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"unable to record safety report"});return};writeJSON(w,202,out)})
 mux.HandleFunc("GET /v1/me/safety/reports",func(w http.ResponseWriter,r *http.Request){if !available(w){return};p,ok:=authenticate(w,r,identity);if !ok{return};items,e:=svc.Mine(r.Context(),p.Subject);if e!=nil{writeJSON(w,500,map[string]string{"error":"unable to load safety reports"});return};writeJSON(w,200,items)})
 mux.HandleFunc("POST /v1/safety/reports/{id}/appeal",func(w http.ResponseWriter,r *http.Request){if !available(w){return};p,ok:=authenticate(w,r,identity);if !ok{return};var in struct{Reason string `json:"reason"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid appeal"});return};out,e:=svc.Appeal(r.Context(),r.PathValue("id"),p.Subject,in.Reason);if errors.Is(e,safety.ErrNotFound){writeJSON(w,404,map[string]string{"error":"report not found"});return};if errors.Is(e,safety.ErrInvalid){writeJSON(w,400,map[string]string{"error":"appeal reason is required"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"unable to record appeal"});return};writeJSON(w,202,out)})
 mux.HandleFunc("GET /v1/safety/review-queue",func(w http.ResponseWriter,r *http.Request){if !available(w){return};p,ok:=authenticate(w,r,identity);if !ok{return};if !(p.HasRole("trust_safety_admin")||p.HasRole("safety_reviewer")){writeJSON(w,403,map[string]string{"error":"safety reviewer role required"});return};items,e:=svc.Queue(r.Context());if e!=nil{writeJSON(w,500,map[string]string{"error":"unable to load review queue"});return};writeJSON(w,200,items)})
 mux.HandleFunc("POST /v1/safety/reports/{id}/decision",func(w http.ResponseWriter,r *http.Request){if !available(w){return};p,ok:=authenticate(w,r,identity);if !ok{return};if !(p.HasRole("trust_safety_admin")||p.HasRole("safety_reviewer")){writeJSON(w,403,map[string]string{"error":"safety reviewer role required"});return};var in struct{Decision string `json:"decision"`;Note string `json:"note"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid decision"});return};out,e:=svc.Decide(r.Context(),r.PathValue("id"),p.Subject,in.Decision,in.Note);if errors.Is(e,safety.ErrNotFound){writeJSON(w,404,map[string]string{"error":"report not found"});return};if errors.Is(e,safety.ErrInvalid){writeJSON(w,400,map[string]string{"error":"decision must be triage, action, dismiss, or close"});return};if e!=nil{writeJSON(w,500,map[string]string{"error":"unable to record decision"});return};writeJSON(w,200,out)})
 return func(){if svc!=nil{svc.Close()}}
}
