import { useMemo } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { StitchTopBar } from '../../components/StitchChrome';
import { Stitch } from '../../lib/stitch-theme';
import { stitchPurpose, stitchScreen } from '../../lib/stitch-screen-catalog';
export default function StitchScreenContract(){const params=useLocalSearchParams<{screen?:string}>();const screen=useMemo(()=>stitchScreen(String(params.screen??'')),[params.screen]);if(!screen)return <SafeAreaView style={s.safe}><StitchTopBar title="Surface not found" showBack showCatalog={false}/><View style={s.center}><Text style={s.title}>Unknown Stitch surface</Text><Pressable style={s.primary} onPress={()=>router.replace('/catalog')}><Text style={s.primaryText}>Open surface catalog</Text></Pressable></View></SafeAreaView>;const routeNeedsContext=!!screen.mobileRoute?.includes('[')||screen.mobileRoute==='/project/funding'||screen.mobileRoute==='/project/contribute';return <SafeAreaView style={s.safe}><StitchTopBar title={screen.title} showBack showCatalog={false}/><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.eyebrow}>{screen.source==='stitch'?'GOOGLE STITCH DESIGN CONTRACT':'I RESPOND DESIGN-SYSTEM EXTENSION'}</Text><Text style={s.title}>{screen.title}</Text><Text style={s.heroBody}>{stitchPurpose(screen)}</Text></View><View style={s.card}><Row label="Domain" value={screen.domain.replaceAll('-',' ')}/><Row label="Status" value={screen.status==='live'?'Backend-backed live surface':'Canonical design; backend contract pending'}/><Row label="Audience" value={screen.roles.join(', ')}/></View>{screen.status==='live'?<View style={s.noticeLive}><Text style={s.noticeTitle}>Functional surface</Text><Text style={s.body}>The live route uses real iRespond APIs. Visibility never grants authority: server roles and resource-level permission envelopes remain decisive.</Text>{screen.mobileRoute&&!routeNeedsContext?<Pressable style={s.primary} onPress={()=>router.push(screen.mobileRoute as never)}><Text style={s.primaryText}>Open live surface</Text></Pressable>:<Text style={s.small}>Open this capability from its project, need or evidence context so the required resource identifier is preserved.</Text>}</View>:<View style={s.noticeDesign}><Text style={s.noticeTitle}>Design contract only</Text><Text style={s.body}>This screen remains part of the canonical Stitch product language, but iRespond does not yet have the required persistence, authorization, audit and API contract. Interactive production actions are intentionally absent rather than mocked.</Text></View>}<View style={s.card}><Text style={s.section}>Canonical design rules</Text><Text style={s.body}>Institutional navy and action green establish trust hierarchy; warm amber is reserved for urgent/report actions. Inter typography, 20px screen padding, 16px cards, restrained hairline borders and 44–52px controls apply here and to every extended surface.</Text><Text style={s.body}>Truth states remain explicit: an observation is not verification; a pledge is not settlement; a designed screen is not an implemented capability.</Text></View></ScrollView></SafeAreaView>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Stitch.color.background},content:{padding:Stitch.space.screen,gap:Stitch.space.base,paddingBottom:40},center:{flex:1,padding:Stitch.space.screen,alignItems:'center',justifyContent:'center',gap:Stitch.space.base},hero:{backgroundColor:Stitch.color.primary,borderRadius:Stitch.radius.hero,padding:Stitch.space.lg,gap:Stitch.space.sm},eyebrow:{...Stitch.type.eyebrow,color:Stitch.color.secondaryFixedDim},title:{...Stitch.type.headline,color:Stitch.color.onPrimary},heroBody:{...Stitch.type.body,color:Stitch.color.primaryFixed},card:{backgroundColor:Stitch.color.surfaceLowest,borderRadius:Stitch.radius.lg,padding:Stitch.space.card,gap:Stitch.space.md,borderWidth:1,borderColor:Stitch.color.outlineVariant},row:{gap:3},rowLabel:{...Stitch.type.eyebrow,color:Stitch.color.outline},rowValue:{...Stitch.type.bodyBold,color:Stitch.color.primary},section:{...Stitch.type.section,color:Stitch.color.primary},body:{...Stitch.type.body,color:Stitch.color.onSurfaceVariant},small:{...Stitch.type.footnote,color:Stitch.color.onSurfaceVariant},noticeLive:{backgroundColor:Stitch.color.secondaryContainer,borderRadius:Stitch.radius.lg,padding:Stitch.space.card,gap:Stitch.space.sm},noticeDesign:{backgroundColor:Stitch.color.surfaceContainer,borderRadius:Stitch.radius.lg,padding:Stitch.space.card,gap:Stitch.space.sm,borderWidth:1,borderColor:Stitch.color.outlineVariant},noticeTitle:{...Stitch.type.card,color:Stitch.color.primary},primary:{minHeight:Stitch.control.primaryHeight,backgroundColor:Stitch.color.primary,borderRadius:Stitch.radius.md,paddingHorizontal:Stitch.space.base,alignItems:'center',justifyContent:'center',marginTop:Stitch.space.sm},primaryText:{...Stitch.type.bodyBold,color:Stitch.color.onPrimary}});
