{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api-ingress
  labels: {app.kubernetes.io/name: irespond, app.kubernetes.io/component: api}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: irespond, app.kubernetes.io/component: api}
  policyTypes: [Ingress]
  ingress:
    - from:
{{- if .Values.networkPolicy.allowSameNamespace }}
        - podSelector: {}
{{- end }}
{{- range .Values.networkPolicy.additionalIngressNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
{{- end }}
      ports:
        - {protocol: TCP, port: 8080}
{{- end }}
