import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

type Project = { id:string; sourceNeedId:string; title:string; description:string; ownerCommunityId:string; projectManagerId?:string; status:string; sdgTags:number[] };
type Milestone = { id:string; title:string; description:string; status:string; sequence:number };
type ContributionNeed = { id:string; kind:string; description:string; quantityNote:string; status:string };
type ProjectDetail = { project:Project; milestones:Milestone[]; contributionNeeds:ContributionNeed[] };

export default function ProjectRoom(){
  const {id}=useLocalSearchParams<{id:string}>();const [detail,setDetail]=useState<ProjectDetail|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  async function load(){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');if(!base||!id){setError('Project API is not configured on this build.');setLoading(false);return}setLoading(true);setError('');try{const response=await fetch(`${base}/v1/projects/${encodeURIComponent(id)}`);if(!response.ok)throw new Error(String(response.status));setDetail((await response.json()) as ProjectDetail)}catch{setError('This Project Room could not be loaded. Check connectivity and try again.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[id]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <Pressable onPress={()=>router.back()}><Text style={styles.back}>← Back</Text></Pressable>
    {loading&&<View style={styles.loading}><ActivityIndicator/><Text style={styles.muted}>Loading Project Room…</Text></View>}
    {!!error&&<View style={styles.notice}><Text style={styles.noticeTitle}>Unable to load</Text><Text style={styles.muted}>{error}</Text><Pressable onPress={load}><Text style={styles.link}>Try again</Text></Pressable></View>}
    {detail&&<>
      <Text style={styles.eyebrow}>ACTION PROJECT</Text><Text style={styles.title}>{detail.project.title}</Text><Text style={styles.description}>{detail.project.description}</Text>
      <View style={styles.statusCard}><Text style={styles.statusLabel}>PROJECT STATUS</Text><Text style={styles.status}>{human(detail.project.status)}</Text><Text style={styles.meta}>{detail.project.sdgTags.length?detail.project.sdgTags.map(n=>`SDG ${n}`).join(' · '):'SDG classification pending'}</Text></View>
      <Text style={styles.section}>Milestones</Text>{detail.milestones.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>Planning has started</Text><Text style={styles.muted}>The community steward has not published delivery milestones yet.</Text></View>:detail.milestones.map(m=><View key={m.id} style={styles.card}><Text style={styles.sequence}>MILESTONE {m.sequence}</Text><Text style={styles.cardTitle}>{m.title}</Text><Text style={styles.muted}>{m.description}</Text><Text style={styles.badge}>{human(m.status)}</Text></View>)}
      <Text style={styles.section}>What this project needs</Text>{detail.contributionNeeds.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>Contribution plan pending</Text><Text style={styles.muted}>Money is only one form of response. The project team will publish needs for time, skills, materials, equipment, access and other abilities here.</Text></View>:detail.contributionNeeds.map(c=><View key={c.id} style={styles.card}><Text style={styles.kind}>{human(c.kind)}</Text><Text style={styles.cardTitle}>{c.description}</Text>{!!c.quantityNote&&<Text style={styles.muted}>{c.quantityNote}</Text>}<Pressable style={styles.secondary}><Text style={styles.secondaryText}>I may be able to help</Text></Pressable></View>)}
      <View style={styles.truth}><Text style={styles.truthTitle}>Outcome over activity</Text><Text style={styles.truthText}>A Project Room is successful when the verified need is solved and the result is maintained—not merely when people post, donate, or volunteer.</Text></View>
    </>}
  </ScrollView></SafeAreaView>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,gap:14,paddingBottom:50},back:{color:'#2D6E9F',fontWeight:'800'},loading:{paddingVertical:30,alignItems:'center',gap:9},muted:{color:'#667788',lineHeight:20},link:{color:'#2D6E9F',fontWeight:'800'},notice:{backgroundColor:'#FFF0EF',borderRadius:16,padding:16,gap:8},noticeTitle:{fontWeight:'900',color:'#8A352F'},eyebrow:{color:'#2D7A56',fontWeight:'900',letterSpacing:1.5},title:{color:'#17324D',fontSize:29,lineHeight:35,fontWeight:'900'},description:{color:'#3D5669',fontSize:16,lineHeight:24},statusCard:{backgroundColor:'#153B5B',borderRadius:19,padding:17,gap:6},statusLabel:{color:'#8ED1B2',fontWeight:'900',fontSize:11,letterSpacing:1.3},status:{color:'white',fontSize:22,fontWeight:'900'},meta:{color:'#D6E2EB'},section:{color:'#17324D',fontSize:21,fontWeight:'900',marginTop:6},card:{backgroundColor:'white',borderRadius:17,padding:16,gap:7},sequence:{color:'#2D7A56',fontWeight:'900',fontSize:11,letterSpacing:1},kind:{color:'#2D6E9F',fontWeight:'900'},cardTitle:{color:'#17324D',fontSize:17,fontWeight:'900'},badge:{alignSelf:'flex-start',backgroundColor:'#E9F5EF',color:'#245840',fontWeight:'800',paddingHorizontal:9,paddingVertical:5,borderRadius:9},secondary:{borderWidth:1,borderColor:'#9CB8CD',borderRadius:12,padding:12,marginTop:4},secondaryText:{color:'#2D6E9F',fontWeight:'900',textAlign:'center'},empty:{backgroundColor:'#EEF3F7',padding:16,borderRadius:16,gap:5},emptyTitle:{color:'#17324D',fontWeight:'900'},truth:{backgroundColor:'#FFF7E7',padding:16,borderRadius:16,gap:5},truthTitle:{color:'#6D4A14',fontWeight:'900'},truthText:{color:'#7D6848',lineHeight:20}})
