import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getAccessToken } from '../../lib/session';

export default function Contribute(){
  const{projectId,needId,kind,description}=useLocalSearchParams<{projectId:string;needId:string;kind?:string;description?:string}>();const[note,setNote]=useState('');const[availability,setAvailability]=useState('');const[saving,setSaving]=useState(false);
  async function submit(){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');if(!base||!projectId||!needId){Alert.alert('Not configured','Contribution API is not available on this build.');return}const token=await getAccessToken();if(!token){router.push('/signin');return}setSaving(true);try{const response=await fetch(`${base}/v1/projects/${encodeURIComponent(projectId)}/contribution-needs/${encodeURIComponent(needId)}/offers`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({note,availabilityNote:availability})});if(response.status===401){router.push('/signin');return}if(!response.ok){const body=await response.json().catch(()=>({error:'Offer could not be submitted'})) as {error?:string};Alert.alert('Offer not submitted',body.error??'Try again.');return}Alert.alert('Offer submitted','The project team can now review how your ability fits the project. An offer is not an automatic assignment or financial commitment.');router.back()}catch{Alert.alert('Offer not submitted','Check connectivity and try again.')}finally{setSaving(false)}}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={styles.back}>← Back to Project Room</Text></Pressable><Text style={styles.eyebrow}>RESPOND WITH YOUR ABILITY</Text><Text style={styles.title}>{kind?human(kind):'Contribute to this project'}</Text>{!!description&&<Text style={styles.description}>{description}</Text>}<View style={styles.notice}><Text style={styles.noticeTitle}>Contribution ≠ commitment</Text><Text style={styles.noticeText}>Tell the team what you may be able to provide. The team must accept and coordinate the offer before it becomes an assigned responsibility.</Text></View><View style={styles.field}><Text style={styles.label}>How can you help?</Text><TextInput value={note} onChangeText={setNote} style={[styles.input,styles.multi]} multiline placeholder="Describe your skill, time, material, equipment, access, care, funding or other ability." placeholderTextColor="#8A98A5"/></View><View style={styles.field}><Text style={styles.label}>Availability or conditions</Text><TextInput value={availability} onChangeText={setAvailability} style={styles.input} placeholder="e.g. Saturdays, 4 hours; delivery within Lagos" placeholderTextColor="#8A98A5"/></View><Pressable style={[styles.primary,saving&&styles.disabled]} disabled={saving} onPress={submit}><Text style={styles.primaryText}>{saving?'Submitting…':'Offer my ability'}</Text></Pressable></ScrollView></SafeAreaView>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,gap:14,paddingBottom:40},back:{color:'#2D6E9F',fontWeight:'800'},eyebrow:{color:'#2D7A56',fontWeight:'900',letterSpacing:1.4},title:{color:'#17324D',fontSize:29,lineHeight:35,fontWeight:'900'},description:{color:'#455E70',fontSize:16,lineHeight:23},notice:{backgroundColor:'#FFF7E7',borderRadius:15,padding:15,gap:5},noticeTitle:{color:'#6D4A14',fontWeight:'900'},noticeText:{color:'#7D6848',lineHeight:20},field:{gap:6},label:{color:'#334B5D',fontWeight:'800'},input:{backgroundColor:'white',borderWidth:1,borderColor:'#D4DEE6',borderRadius:13,padding:13,color:'#17324D'},multi:{minHeight:120,textAlignVertical:'top'},primary:{backgroundColor:'#153B5B',padding:16,borderRadius:14},primaryText:{color:'white',fontWeight:'900',textAlign:'center'},disabled:{opacity:.55}})
