import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getAccessToken } from '../../lib/session';

type Plan={projectId:string;currency:string;targetMinor:number;communityCounterpartMinor:number;externalTargetMinor:number;status:string;pledgedMinor:number;confirmedMinor:number;updatedAt:string};
const classes=[['external_donation','External donation'],['community_counterpart','Community counterpart'],['matching_commitment','Matching commitment']] as const;

export default function ProjectFunding(){
 const{projectId}=useLocalSearchParams<{projectId:string}>();const[plan,setPlan]=useState<Plan|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[amount,setAmount]=useState('');const[klass,setKlass]=useState<string>('external_donation');const[saving,setSaving]=useState(false);const[target,setTarget]=useState('');const[counterpart,setCounterpart]=useState('');const[currency,setCurrency]=useState('NGN');
 async function auth(){const base=process.env.EXPO_PUBLIC_API_BASE_URL?.replace(/\/$/,'');const token=await getAccessToken();if(!base){setError('The funding API is not configured on this build.');return null}if(!token){router.replace('/signin');return null}return{base,token}}
 async function load(){const a=await auth();if(!a||!projectId){setLoading(false);return}setLoading(true);setError('');try{const r=await fetch(`${a.base}/v1/projects/${encodeURIComponent(projectId)}/funding`,{headers:{Authorization:`Bearer ${a.token}`}});if(r.status===404){setPlan(null);return}if(r.status===401){router.replace('/signin');return}if(!r.ok)throw new Error('load');const p=await r.json() as Plan;setPlan(p);setCurrency(p.currency);setTarget(String(p.targetMinor/100));setCounterpart(String(p.communityCounterpartMinor/100))}catch{setError('Funding information could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId]);
 async function pledge(){const a=await auth();if(!a||!projectId)return;const major=Number(amount);if(!Number.isFinite(major)||major<=0){Alert.alert('Enter a pledge amount','Use an amount greater than zero.');return}setSaving(true);setError('');try{const r=await fetch(`${a.base}/v1/projects/${encodeURIComponent(projectId)}/funding/pledges`,{method:'POST',headers:{Authorization:`Bearer ${a.token}`,'Content-Type':'application/json'},body:JSON.stringify({contributionClass:klass,amountMinor:Math.round(major*100)})});if(!r.ok)throw new Error('pledge');setAmount('');await load();Alert.alert('Pledge recorded','This records your commitment only. iRespond has not charged, held or moved any money.')}catch{setError('Your pledge could not be recorded.')}finally{setSaving(false)}}
 async function configure(){const a=await auth();if(!a||!projectId)return;const total=Number(target),community=Number(counterpart);if(!Number.isFinite(total)||!Number.isFinite(community)||total<=0||community<0||community>total){Alert.alert('Check the funding plan','Target must be positive and community counterpart cannot exceed the target.');return}setSaving(true);setError('');try{const r=await fetch(`${a.base}/v1/projects/${encodeURIComponent(projectId)}/funding`,{method:'PUT',headers:{Authorization:`Bearer ${a.token}`,'Content-Type':'application/json'},body:JSON.stringify({currency:currency.toUpperCase(),targetMinor:Math.round(total*100),communityCounterpartMinor:Math.round(community*100)})});if(r.status===403){Alert.alert('Steward access required','Only an authorized project manager or community steward can change the funding plan.');return}if(!r.ok)throw new Error('plan');setPlan(await r.json() as Plan);Alert.alert('Funding plan published','The community counterpart and external target are now transparent.')}catch{setError('The funding plan could not be saved.')}finally{setSaving(false)}}
 const pct=plan?.targetMinor?Math.min(100,Math.round(plan.pledgedMinor/plan.targetMinor*100)):0;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Back</Text></Pressable><Text style={s.eyebrow}>COUNTERPART FUNDING</Text><Text style={s.title}>Shared responsibility, transparent support</Text><Text style={s.intro}>Community contribution and external support are shown separately. A pledge is a commitment—not proof that money has been paid or settled.</Text>{loading&&<ActivityIndicator/>}{!!error&&<View style={s.error}><Text style={s.errorText}>{error}</Text></View>}
 {plan?<><View style={s.hero}><Text style={s.heroLabel}>PROJECT FUNDING TARGET</Text><Text style={s.heroAmount}>{money(plan.targetMinor,plan.currency)}</Text><Text style={s.heroMeta}>{pct}% pledged · {money(plan.confirmedMinor,plan.currency)} externally confirmed</Text><View style={s.bar}><View style={[s.fill,{width:`${pct}%` as `${number}%`}]}/></View></View><View style={s.split}><Metric label="Community counterpart" value={money(plan.communityCounterpartMinor,plan.currency)}/><Metric label="External target" value={money(plan.externalTargetMinor,plan.currency)}/><Metric label="Total pledged" value={money(plan.pledgedMinor,plan.currency)}/></View><View style={s.card}><Text style={s.section}>Make a pledge</Text><TextInput style={s.input} keyboardType="decimal-pad" placeholder={`Amount in ${plan.currency}`} value={amount} onChangeText={setAmount}/><View style={s.chips}>{classes.map(([id,label])=><Pressable key={id} onPress={()=>setKlass(id)} style={[s.chip,klass===id&&s.chipOn]}><Text style={[s.chipText,klass===id&&s.chipTextOn]}>{label}</Text></Pressable>)}</View><Pressable disabled={saving} style={s.primary} onPress={()=>void pledge()}><Text style={s.primaryText}>{saving?'Recording…':'Record my pledge'}</Text></Pressable><Text style={s.note}>No payment details are collected here. Regulated fund movement will occur only through the governed payment plane when enabled.</Text></View></>:<View style={s.empty}><Text style={s.section}>Funding plan not yet published</Text><Text style={s.intro}>The project may still accept time, skills, materials and other non-cash contributions in its Project Room.</Text></View>}
 <View style={s.card}><Text style={s.section}>Project steward controls</Text><Text style={s.note}>The server verifies your project role before accepting changes.</Text><TextInput style={s.input} autoCapitalize="characters" maxLength={3} value={currency} onChangeText={setCurrency} placeholder="Currency e.g. NGN"/><TextInput style={s.input} keyboardType="decimal-pad" value={target} onChangeText={setTarget} placeholder="Total project funding target"/><TextInput style={s.input} keyboardType="decimal-pad" value={counterpart} onChangeText={setCounterpart} placeholder="Community counterpart amount"/><Pressable disabled={saving} style={s.secondary} onPress={()=>void configure()}><Text style={s.secondaryText}>Publish / update funding plan</Text></Pressable></View>
 </ScrollView></SafeAreaView>
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
function money(minor:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(minor/100)}catch{return `${currency} ${(minor/100).toLocaleString()}`}}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F8FB'},content:{padding:20,gap:14,paddingBottom:50},back:{color:'#2D6E9F',fontWeight:'800'},eyebrow:{color:'#2D7A56',fontWeight:'900',letterSpacing:1.4},title:{fontSize:29,lineHeight:35,fontWeight:'900',color:'#17324D'},intro:{color:'#617485',lineHeight:21},error:{backgroundColor:'#FFF0EF',padding:14,borderRadius:14},errorText:{color:'#8A352F',fontWeight:'700'},hero:{backgroundColor:'#153B5B',borderRadius:20,padding:18,gap:7},heroLabel:{color:'#8ED1B2',fontWeight:'900',fontSize:11,letterSpacing:1.2},heroAmount:{color:'white',fontSize:28,fontWeight:'900'},heroMeta:{color:'#D6E2EB'},bar:{height:8,backgroundColor:'#34566F',borderRadius:8,overflow:'hidden'},fill:{height:8,backgroundColor:'#8ED1B2'},split:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{backgroundColor:'white',borderRadius:14,padding:12,minWidth:'47%',flexGrow:1},metricLabel:{color:'#6B7B88',fontSize:11,fontWeight:'800'},metricValue:{color:'#17324D',fontSize:16,fontWeight:'900',marginTop:3},card:{backgroundColor:'white',borderRadius:18,padding:16,gap:10},section:{fontSize:18,fontWeight:'900',color:'#17324D'},input:{borderWidth:1,borderColor:'#D2DDE5',borderRadius:12,padding:12,backgroundColor:'#FBFCFD'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#AABBC8',borderRadius:99,paddingHorizontal:10,paddingVertical:8},chipOn:{backgroundColor:'#E9F5EF',borderColor:'#4B9270'},chipText:{color:'#526778',fontWeight:'700',fontSize:12},chipTextOn:{color:'#245840'},primary:{backgroundColor:'#153B5B',padding:14,borderRadius:13},primaryText:{color:'white',textAlign:'center',fontWeight:'900'},secondary:{borderWidth:1,borderColor:'#7E9DB3',padding:13,borderRadius:13},secondaryText:{color:'#2D6E9F',textAlign:'center',fontWeight:'900'},note:{color:'#738390',fontSize:12,lineHeight:17},empty:{backgroundColor:'#EEF3F7',borderRadius:17,padding:16,gap:6}});
